# Generated by Django 2.2.3 on 2019-07-29 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='productName',
        ),
    ]
